Parameters:

  EnvironmentName:
      Description: An environment name that will be prefixed to resource names
      Type: String

Resources:
  MyLaunchTemplateKubernetes:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: "KubernetesServerTemplate"
      LaunchTemplateData:
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            sudo apt-get update
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && \
            sudo chmod +x /bin/hadolint
            sudo apt install docker.io -y
            sudo systemctl start docker
            sudo systemctl enable docker
            #install conntrack
            sudo apt install conntrack -y
            #install kubectl
            curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
            sudo apt install socat -y
            # install minikube
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
            sudo minikube start --vm-driver=none

        InstanceType: t3.medium
        DisableApiTermination: 'true'
        KeyName: project5
        ImageId: ami-0eb89db7593b5d434
        SecurityGroupIds:
          - Fn::ImportValue:
             !Sub "${EnvironmentName}-SECG"
        BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          Ebs:
            VolumeSize: '20'

  KubernetesServer:
    Type: AWS::EC2::Instance
    Properties:
      Tags: 
        - Key: "Name"
          Value: "Green"
        - Key: "Project"
          Value: "Capstone" 
      SubnetId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-PUB1-SN"
      LaunchTemplate: 
        LaunchTemplateId: !Ref MyLaunchTemplateKubernetes
        Version: 1